### ISSUE TITLE
A user should be able to scroll earlier in the day to see past events//show 'Now!'

### ISSUE THREAD

**Issue by GregoryElliott** [eecs394-spr15/PocketAssistant#16]

**Comment by mingyueding** [comment]
Could we change this issue to highlight the ongoing event?

**Comment by GregoryElliott** [comment]
Yeah I think that would be fine. This is another thing we should probably ask our client about 

```
 On Thursday, May 14, 2015 1:02 AM, mingyueding <notifications@github.com> wrote:
```

 Could we change this issue to highlight the ongoing event?—
